//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   北海道,石狩市花川,43.172,141.315
        ///北海道,石狩市聚富,43.275,141.418
        ///北海道,札幌中央区北２条,43.060,141.328
        ///北海道,江別市高砂町,43.103,141.537
        ///北海道,千歳市北栄,42.827,141.642
        ///北海道,新千歳空港,42.783,141.678
        ///北海道,恵庭市漁平,42.843,141.447
        ///北海道,八雲町上の湯,42.120,140.367
        ///北海道,函館市美原,41.817,140.753
        ///北海道,函館市尾札部町,41.890,141.028
        ///北海道,七飯町桜町,41.903,140.688
        ///北海道,渡島森町御幸町,42.105,140.577
        ///北海道,渡島松前町福山,41.430,140.110
        ///北海道,渡島松前町清部,41.525,140.007
        ///北海道,知内町小谷石,41.532,140.413
        ///北海道,檜山江差町姥神,41.868,140.125
        ///北海道,せたな町北檜山区豊岡,42.423,139.877
        ///北海道,小樽市勝納町,43.183,141.017
        ///北海道,積丹町日司町,43.355,140.472
        ///北海道,余市町朝日町,43. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObservationPoints {
            get {
                return ResourceManager.GetString("ObservationPoints", resourceCulture);
            }
        }
    }
}
