//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ,あきる野市伊奈,35.732,139.255
        ///,あさぎり町上,32.201,130.895
        ///,あさぎり町免田東,32.226,130.895
        ///,あさぎり町岡原,32.226,130.925
        ///,あさぎり町深田,32.226,130.873
        ///,あさぎり町須惠,32.251,130.895
        ///,あま市七宝町,35.167,136.801
        ///,あま市木田,35.197,136.785
        ///,あま市甚目寺,35.195,136.820
        ///,あわら市国影,36.218,136.202
        ///,あわら市市姫,36.204,136.226
        ///,いすみ市国府台,35.283,140.311
        ///,いすみ市大原,35.251,140.385
        ///,いすみ市岬町長者,35.297,140.385
        ///,いちき串木野市湊町,31.686,130.285
        ///,いちき串木野市緑町,31.704,130.270
        ///,いなべ市北勢町阿下喜,35.149,136.523
        ///,いなべ市員弁町笠田新田,35.113,136.561
        ///,いなべ市大安町大井田,35.090,136.537
        ///,いなべ市藤原町市場,35.170,136.495
        ///,い [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObservationPoints {
            get {
                return ResourceManager.GetString("ObservationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10,北海道,北海道,北海道 石狩,43.062,141.354
        ///15,北海道,北海道,北海道 渡島,41.820,140.753
        ///20,北海道,北海道,北海道 檜山,41.859,140.128
        ///25,北海道,北海道,北海道 後志,42.902,140.756
        ///30,北海道,北海道,北海道 空知,43.198,141.767
        ///35,北海道,北海道,北海道 上川,43.808,142.439
        ///40,北海道,北海道,北海道 留萌,43.935,141.656
        ///45,北海道,北海道,北海道 宗谷,45.398,141.700
        ///50,北海道,北海道,北海道 網走,44.027,144.261
        ///55,北海道,北海道,北海道 胆振,42.321,140.972
        ///60,北海道,北海道,北海道 日高,42.173,142.768
        ///65,北海道,北海道,北海道 十勝,42.930,143.208
        ///70,北海道,北海道,北海道 釧路,42.977,144.345
        ///75,北海道,北海道,北海道 根室,43.330,145.585
        ///100,東北,青森,青森津軽,40.759,140.428
        ///105,東 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserquakeAreas {
            get {
                return ResourceManager.GetString("UserquakeAreas", resourceCulture);
            }
        }
    }
}
