//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfClient.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   地域コード(文字列型),地域コード(数値型),地方,都道府県,地域,緯度,経度
        ///900,900,未設定,,地域未設定,,
        ///901,901,不明,,地域不明,,
        ///905,905,外国,,日本以外,,
        ///010,10,北海道,北海道,北海道 石狩,43.062,141.354
        ///015,15,北海道,北海道,北海道 渡島,41.820,140.753
        ///020,20,北海道,北海道,北海道 檜山,41.859,140.128
        ///025,25,北海道,北海道,北海道 後志,42.902,140.756
        ///030,30,北海道,北海道,北海道 空知,43.198,141.767
        ///035,35,北海道,北海道,北海道 上川,43.808,142.439
        ///040,40,北海道,北海道,北海道 留萌,43.935,141.656
        ///045,45,北海道,北海道,北海道 宗谷,45.398,141.700
        ///050,50,北海道,北海道,北海道 網走,44.027,144.261
        ///055,55,北海道,北海道,北海道 胆振,42.321,140.972
        ///060,60,北海道,北海道,北海道 日高,42.173, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string epsp_area {
            get {
                return ResourceManager.GetString("epsp-area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon p2pquake {
            get {
                object obj = ResourceManager.GetObject("p2pquake", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   北海道,ほっかいどう
        ///青森県,あおもりけん
        ///岩手県,いわてけん
        ///宮城県,みやぎけん
        ///秋田県,あきたけん
        ///山形県,やまがたけん
        ///福島県,ふくしまけん
        ///茨城県,いばらきけん
        ///栃木県,とちぎけん
        ///群馬県,ぐんまけん
        ///埼玉県,さいたまけん
        ///千葉県,ちばけん
        ///東京都,とうきょうと
        ///神奈川県,かながわけん
        ///新潟県,にいがたけん
        ///富山県,とやまけん
        ///石川県,いしかわけん
        ///福井県,ふくいけん
        ///山梨県,やまなしけん
        ///長野県,ながのけん
        ///岐阜県,ぎふけん
        ///静岡県,しずおかけん
        ///愛知県,あいちけん
        ///三重県,みえけん
        ///滋賀県,しがけん
        ///京都府,きょうとふ
        ///大阪府,おおさかふ
        ///兵庫県,ひょうごけん
        ///奈良県,ならけん
        ///和歌山県,わかやまけん
        ///鳥取県,とっとりけん
        ///島根県,しまねけん
        ///岡山県,おかやまけん
        ///広島県,ひろしまけん
        ///山口県,やまぐちけん
        ///徳島県,とくしまけん
        ///香川県,かがわけん
        ///愛媛県,えひめけん
        ///高知県,こうちけん
        ///福岡県,ふくおかけん
        ///佐賀県,さがけん
        ///長崎県,ながさきけん
        ///熊本県,くまもとけん
        ///大分県,おおいたけん
        ///宮崎県,みやざきけん
        ///鹿児島県,かごしまけん
        ///沖縄県,おきなわけん
        ///石狩地方北部,いしかりちほうほくぶ
        ///石 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Points2Kana {
            get {
                return ResourceManager.GetString("Points2Kana", resourceCulture);
            }
        }
    }
}
