//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PointResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PointResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map.PointResource", typeof(PointResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;,&quot;features&quot;:[{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[141.4039,43.7378],[141.4173,43.7112],[141.4906,43.6844],[141.5833,43.6099],[141.5949,43.5838],[141.6001,43.5846],[141.6182,43.5779],[141.6235,43.5419],[141.6514,43.5138],[141.7278,43.4714],[141.7223,43.4596],[141.5976,43.3848],[141.5811,43.3527],[141.62,43.2835],[141.6543,43.2861],[141.6546,43.2837],[141.6462,43.2694],[141.673,43.2281],[141.654,43.2208],[141.6489,43.1895],[141.6104,43.1686],[141.623 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaGeoJsons {
            get {
                return ResourceManager.GetString("AreaGeoJsons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県名,区域名,緯度,経度
        ///北海道,石狩地方北部,43.632,141.493
        ///北海道,石狩地方中部,43.057,141.367
        ///北海道,石狩地方南部,42.836,141.493
        ///北海道,後志地方北部,43.193,140.988
        ///北海道,後志地方東部,42.820,140.883
        ///北海道,後志地方西部,42.763,140.290
        ///北海道,空知地方北部,43.723,142.057
        ///北海道,空知地方中部,43.492,141.906
        ///北海道,空知地方南部,43.196,141.781
        ///北海道,渡島地方北部,42.391,140.266
        ///北海道,渡島地方東部,41.873,140.838
        ///北海道,渡島地方西部,41.592,140.342
        ///北海道,檜山地方,41.894,140.224
        ///北海道,北海道奥尻島,42.149,139.471
        ///北海道,胆振地方西部,42.606,140.746
        ///北海道,胆振地方中東部,42.660,141.658
        ///北海道,日高地方西部,42.674,142.399
        ///北海道,日高地方中部,42.428,142.690
        ///北海道,日高地方東部 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100,石狩地方北部
        ///101,石狩地方中部
        ///102,石狩地方南部
        ///105,渡島地方北部
        ///106,渡島地方東部
        ///107,渡島地方西部
        ///110,檜山地方
        ///115,後志地方北部
        ///116,後志地方東部
        ///117,後志地方西部
        ///119,北海道奥尻島
        ///120,空知地方北部
        ///121,空知地方中部
        ///122,空知地方南部
        ///125,上川地方北部
        ///126,上川地方中部
        ///127,上川地方南部
        ///130,留萌地方中北部
        ///131,留萌地方南部
        ///135,宗谷地方北部
        ///136,宗谷地方南部
        ///139,北海道利尻礼文
        ///140,網走地方
        ///141,北見地方
        ///142,紋別地方
        ///145,胆振地方西部
        ///146,胆振地方中東部
        ///150,日高地方西部
        ///151,日高地方中部
        ///152,日高地方東部
        ///155,十勝地方北部
        ///156,十勝地方中部
        ///157,十勝地方南部
        ///160,釧路地方北部
        ///161,釧路地方中南部
        ///165,根室地方北部
        ///166,根室地方中部
        ///167,根室地方南部
        ///200,青森県津軽北部
        ///201,青森県津軽南部
        ///202,青森県三八上北
        ///203,青森県下北
        ///210,岩手県沿岸北 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EarthquakeAreaCodes {
            get {
                return ResourceManager.GetString("EarthquakeAreaCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EEW府県予報区地域コード,区域コード1...
        ///160,100,101,102,115,116,117,120,121,122
        ///161,105,106,107,110,119,145,146,150,151,152
        ///162,125,126,127,130,131,135,136,139
        ///163,140,141,142,155,156,157,160,161,165,166,167
        ///164,200,201,202,203
        ///165,210,211,212,213
        ///166,220,222,221
        ///167,230,231,232,233
        ///168,240,241,242,243
        ///169,250,251,252
        ///170,300,301
        ///171,310,311
        ///172,320,321
        ///173,330,331,332
        ///174,340,341,342
        ///175,350,351,352
        ///176,355,356,354,357,358
        ///177,359
        ///178,360,361
        ///179,370,371,372,375
        ///180,380,381
        ///181,390,391
        ///182,400,401
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EEWPrefs2EarthquakeAreaCodes {
            get {
                return ResourceManager.GetString("EEWPrefs2EarthquakeAreaCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   北海道,石狩市花川,43.17,141.32,気象庁
        ///北海道,石狩市聚富,43.28,141.42,気象庁
        ///北海道,石狩市厚田,43.40,141.43,防災科研
        ///北海道,石狩市浜益,43.60,141.39,防災科研
        ///北海道,石狩市花畔,43.17,141.30,防災科研
        ///北海道,当別町白樺,43.22,141.52,防災科研
        ///北海道,新篠津村第４７線,43.23,141.65,地方公共団体
        ///北海道,札幌中央区北２条,43.06,141.33,気象庁
        ///北海道,札幌中央区南４条,43.05,141.34,地方公共団体
        ///北海道,札幌北区太平,43.14,141.35,防災科研
        ///北海道,札幌北区篠路,43.14,141.36,地方公共団体
        ///北海道,札幌北区新琴似,43.11,141.33,地方公共団体
        ///北海道,札幌東区元町,43.09,141.37,地方公共団体
        ///北海道,札幌白石区北郷,43.06,141.42,地方公共団体
        ///北海道,札幌豊平区月寒東,43.03,141.40,地方公共団体
        ///北海道,札幌南区定山渓温泉,42.97,141.18,防災科研
        ///北海道,札幌南区川沿,43. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100,北海道太平洋沿岸東部
        ///101,北海道太平洋沿岸中部
        ///102,北海道太平洋沿岸西部
        ///110,北海道日本海沿岸北部
        ///111,北海道日本海沿岸南部
        ///120,オホーツク海沿岸
        ///200,青森県日本海沿岸
        ///201,青森県太平洋沿岸
        ///202,陸奥湾
        ///210,岩手県
        ///220,宮城県
        ///230,秋田県
        ///240,山形県
        ///250,福島県
        ///300,茨城県
        ///310,千葉県九十九里・外房
        ///311,千葉県内房
        ///312,東京湾内湾
        ///320,伊豆諸島
        ///321,小笠原諸島
        ///330,相模湾・三浦半島
        ///340,新潟県上中下越
        ///341,佐渡
        ///350,富山県
        ///360,石川県能登
        ///361,石川県加賀
        ///370,福井県
        ///380,静岡県
        ///390,愛知県外海
        ///391,伊勢・三河湾
        ///400,三重県南部
        ///500,京都府
        ///510,大阪府
        ///520,兵庫県北部
        ///521,兵庫県瀬戸内海沿岸
        ///522,淡路島南部
        ///530,和歌山県
        ///540,鳥取県
        ///550,島根県出雲・石見
        ///551,隠岐
        ///560,岡山県
        ///570,広島県
        ///580,徳島県
        ///590,香川県
        ///600,愛媛県宇和海沿岸
        ///601, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TsunamiAreaCodes {
            get {
                return ResourceManager.GetString("TsunamiAreaCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;,&quot;features&quot;:[{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiLineString&quot;,&quot;coordinates&quot;:[[[145.5976,43.2217],[145.609,43.2112],[145.5887,43.2064],[145.5976,43.2217]],[[146.0166,43.3784],[146.0064,43.3604],[145.9861,43.369],[146.0166,43.3784]],[[146.0986,43.4481],[146.1083,43.4312],[146.0841,43.4135],[146.0248,43.4083],[146.0472,43.4316],[146.0869,43.4254],[146.0829,43.4397],[146.0986,43.4481]],[[145.8877,43.4622],[145.9051,43.4476],[145.9501,43.4539],[145.9342,43.4401],[145.9554,43.4249 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TsunamiAreaGeoJsons {
            get {
                return ResourceManager.GetString("TsunamiAreaGeoJsons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///&quot;type&quot;: &quot;FeatureCollection&quot;,
        ///&quot;features&quot;: [
        ///{ &quot;type&quot;: &quot;Feature&quot;, &quot;properties&quot;: { &quot;code&quot;: &quot;12201&quot; }, &quot;geometry&quot;: { &quot;type&quot;: &quot;MultiPolygon&quot;, &quot;coordinates&quot;: [ [ [ [ 141.6243, 38.8854 ], [ 141.6343, 38.8674 ], [ 141.6224, 38.8514 ], [ 141.6377, 38.8409 ], [ 141.6244, 38.8302 ], [ 141.6017, 38.8738 ], [ 141.6243, 38.8854 ] ] ], [ [ [ 141.5108, 39.0024 ], [ 141.6317, 38.9707 ], [ 141.6319, 38.9707 ], [ 141.6483, 38.9425 ], [ 141.6342, 38.9302 ], [ 141.6532, 38.9191 ], [ 141.6747, 38.8583 ], [ 141.637, 38.8852  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserquakeAreaGeoJsons {
            get {
                return ResourceManager.GetString("UserquakeAreaGeoJsons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域コード,地方名,都道府県名,地域名,緯度,経度
        ///010,北海道,北海道,北海道 石狩,43.062,141.354
        ///015,北海道,北海道,北海道 渡島,41.820,140.753
        ///020,北海道,北海道,北海道 檜山,41.859,140.128
        ///025,北海道,北海道,北海道 後志,42.902,140.756
        ///030,北海道,北海道,北海道 空知,43.198,141.767
        ///035,北海道,北海道,北海道 上川,43.808,142.439
        ///040,北海道,北海道,北海道 留萌,43.935,141.656
        ///045,北海道,北海道,北海道 宗谷,45.398,141.700
        ///050,北海道,北海道,北海道 網走,44.027,144.261
        ///055,北海道,北海道,北海道 胆振,42.321,140.972
        ///060,北海道,北海道,北海道 日高,42.173,142.768
        ///065,北海道,北海道,北海道 十勝,42.930,143.208
        ///070,北海道,北海道,北海道 釧路,42.977,144.345
        ///075,北海道,北海道,北海道 根室,43.330,145. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserquakeAreas {
            get {
                return ResourceManager.GetString("UserquakeAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域コード,区域コード1,区域コード2,区域コード3
        ///010,100,101,102
        ///015,105,106,107
        ///020,110,119
        ///025,115,116,117
        ///030,120,121,122
        ///035,125,126,127
        ///040,130,131
        ///045,135,136,139
        ///050,140,141,142
        ///055,145,146
        ///065,155,156,157
        ///060,150,151,152
        ///070,160,161
        ///075,165,166,167
        ///100,200,201
        ///105,202
        ///106,203
        ///110,210
        ///111,211
        ///115,212,213
        ///120,220,12201,12202
        ///125,221,12211,12212
        ///130,230,231
        ///135,232,233
        ///140,240
        ///141,241
        ///142,242
        ///143,243
        ///150,250
        ///151,251
        ///152,252
        ///200,300
        ///205,301
        ///210,310
        ///215,311
        ///220,320
        ///225,321
        ///230,330
        ///231,33 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserquakeAreas2EarthquakeAreaCodes {
            get {
                return ResourceManager.GetString("UserquakeAreas2EarthquakeAreaCodes", resourceCulture);
            }
        }
    }
}
