//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PointResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PointResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map.PointResource", typeof(PointResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   都道府県,区域名,緯度,経度
        ///北海道,石狩地方北部,43.632,141.493
        ///北海道,石狩地方中部,43.057,141.367
        ///北海道,石狩地方南部,42.836,141.493
        ///北海道,後志地方北部,43.193,140.988
        ///北海道,後志地方東部,42.820,140.883
        ///北海道,後志地方西部,42.763,140.290
        ///北海道,空知地方北部,43.723,142.057
        ///北海道,空知地方中部,43.492,141.906
        ///北海道,空知地方南部,43.196,141.781
        ///北海道,渡島地方北部,42.391,140.266
        ///北海道,渡島地方東部,41.873,140.838
        ///北海道,渡島地方西部,41.592,140.342
        ///北海道,檜山地方,41.894,140.224
        ///北海道,北海道奥尻島,42.149,139.471
        ///北海道,胆振地方西部,42.606,140.746
        ///北海道,胆振地方中東部,42.660,141.658
        ///北海道,日高地方西部,42.674,142.399
        ///北海道,日高地方中部,42.428,142.690
        ///北海道,日高地方東部,42.170,143.064
        ///北海道, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県,観測点名,緯度,経度,種類
        ///北海道,石狩市花川,43.17,141.32,気象庁
        ///北海道,石狩市聚富,43.28,141.42,気象庁
        ///北海道,石狩市厚田,43.4,141.43,防災科研
        ///北海道,石狩市浜益,43.6,141.39,防災科研
        ///北海道,石狩市花畔,43.17,141.3,防災科研
        ///北海道,当別町白樺,43.22,141.52,防災科研
        ///北海道,新篠津村第４７線,43.23,141.65,地方公共団体
        ///北海道,札幌中央区北２条,43.06,141.33,気象庁
        ///北海道,札幌中央区南４条,43.05,141.34,地方公共団体
        ///北海道,札幌北区太平,43.14,141.35,防災科研
        ///北海道,札幌北区篠路,43.14,141.36,地方公共団体
        ///北海道,札幌北区新琴似,43.11,141.33,地方公共団体
        ///北海道,札幌東区元町,43.09,141.37,地方公共団体
        ///北海道,札幌白石区北郷,43.06,141.42,地方公共団体
        ///北海道,札幌豊平区月寒東,43.03,141.4,地方公共団体
        ///北海道,札幌南区定山渓温泉,42.97,141.17,防災科研
        ///北海道,札幌南区川沿,43.0 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域コード,地方,都道府県,地域,緯度,経度
        ///10,北海道,北海道,北海道 石狩,43.062,141.354
        ///15,北海道,北海道,北海道 渡島,41.820,140.753
        ///20,北海道,北海道,北海道 檜山,41.859,140.128
        ///25,北海道,北海道,北海道 後志,42.902,140.756
        ///30,北海道,北海道,北海道 空知,43.198,141.767
        ///35,北海道,北海道,北海道 上川,43.808,142.439
        ///40,北海道,北海道,北海道 留萌,43.935,141.656
        ///45,北海道,北海道,北海道 宗谷,45.398,141.700
        ///50,北海道,北海道,北海道 網走,44.027,144.261
        ///55,北海道,北海道,北海道 胆振,42.321,140.972
        ///60,北海道,北海道,北海道 日高,42.173,142.768
        ///65,北海道,北海道,北海道 十勝,42.930,143.208
        ///70,北海道,北海道,北海道 釧路,42.977,144.345
        ///75,北海道,北海道,北海道 根室,43.330,145.585
        ///100,東北,青森,青森津軽,40.759,140.4 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserquakeAreas {
            get {
                return ResourceManager.GetString("UserquakeAreas", resourceCulture);
            }
        }
    }
}
